default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: 
  password: 

development:
  <<: *default
  database: db/mosaics_development

test:
  <<: *default
  database: db/mosaics_test

production:
  <<: *default
  database: db/mosaics_production
